cycle trough images
adelajaworowska/AA-adelasphotography pull request #1
Opened 2021-11-14 18:01 UTC by Much4cho

2021-11-14 18:06 UTC, aszulc97 requested changes
jezus maria

2021-11-14 18:07 UTC, Much4cho commented
> jezus maria

imglish plz

2021-11-14 18:07 UTC, aszulc97 commented
Jesús María

2021-11-14 18:10 UTC, aszulc97 requested changes

2021-11-14 18:10 UTC, aszulc97 commented on src/app/main-page/main-page.component.ts
> +  prepareListOfImages(): void{
The plan was to make it in a dynamic way, so whenever user adds a new pic to a 'img' folder, the code is going to update our site xoxo

2021-11-14 18:10 UTC, aszulc97 commented on src/app/main-page/main-page.component.ts
> +  prepareListOfImages(): void{
what a professionalist *clap* *clap* *clap*

2021-11-15 12:12 UTC, Much4cho commented on src/app/main-page/main-page.component.ts
> +  prepareListOfImages(): void{
Added a python script that will create us a list of files as a mean-time solution

2021-11-15 12:20 UTC, aszulc97 approved these changes
if it works, it's fine

2021-11-15 12:23 UTC, merged